name: Static Export CI

on:
  push:
    branches: [ static ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: yarn.lock
    - run: yarn
    - run: yarn build && yarn next export
    - uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: out
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
